### ISSUE TITLE
Result page print optimization for Firefox

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1013]
Currently printing a course's results page (which is the only one we're optimizing for) only really works in Chrome.
The page breaks in Firefox are weirdly placed and some of the content is rendered below the page. It should be possible to use the print function in Firefox (with activated Option `Print Background (colors & images)` to create a nice PDF export of a course's results.

**Comment by karyon** [comment]
the bootstrap 4 final changelog lists print style improvements, this might be worth testing again when we have updated to that.

**Comment by janno42** [comment]
this is still broken in our current bootstrap 4 layout

**Comment by janno42** [comment]
printing seems to work in the current firefox version. because firefox does not have an included "save to pdf" option, external pdf printers must be used. there might be remaining problems in the resulting pdfs because some of the printers export the page as a large image instead of text objects, but this is not a problem on our end.
