### ISSUE TITLE
Generalize email template and faq test data

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1069]
The email templates and faq questions/answers in the test data should be more generalized and abstracted from the current HPI specific phrasing.

**Comment by janno42** [comment]
Email addresses and URLs in the templates should be filled from the settings file.

**Comment by karyon** [comment]
could you detail how you imagine that to work? because we can't access the settings from the json file.

**Comment by janno42** [comment]
the templates can have a variable that is filled during rendering when sending the emails.
