### ISSUE TITLE
Extend anonymize script

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1091]
The anonymize script should optimally (not all of that needs to be done for a PR):
- randomly select degrees for courses
- randomly select course types for courses
- replace email template texts with default values (there might be names, urls and emails in there)
- regenerate course names (maybe take them from list and not just shuffle them around)
- regenerate reward point redemption event names (maybe take them from list and not just shuffle them around)
- regenerate questionnaire names (maybe take them from list)
- regenerate questions (maybe take them from list)
- remove all login keys
- have at least one test. maybe use test_data.json?

**Comment by karyon** [comment]
It's not clear to me why shuffling course names is not enough. Course names are public information. Same for questionnaire names which are rather generic. Reward point redemption event names are likewise nothing that needs to be protected. Alright, maybe there are some questions that are specific enough to necessitate some filtering. Or can you give examples for the other categories?

**Comment by janno42** [comment]
Private courses and their questionnaires aren't public information.

**Comment by karyon** [comment]
True. Then i would like to have the lists generated and filtered from production data. I can do that, if I don't have the clearance for that you'll have to do it ;) you think we should have multiple lists of course names? Single results come to mind since they are titled differently, bachelors projects as well, but the effort is probably not worth it... Or we don't use the lists and simply exclude private courses and questionnaires used exclusively in private courses.

**Comment by janno42** [comment]
By excluding do you mean completely removing private courses from the data? I think it would be better to have some private courses in the test data as well.
I'm fine with having lists generated from production data. And I don't think we have to take course types into account when choosing names.

**Comment by karyon** [comment]
no, i meant excluding private course's names when shuffling the names around and duplicate some other names instead. same for the questionnaires, private courses could simply get some of the "normal" questionnaires.

**Comment by marcelgarus** [comment]
What's still left to do:
* anonymize email templates
* randomize questionnaire names
* randomize questionnaire questions

**Comment by janno42** [comment]
the current state is fine for now.
