### ISSUE TITLE
Text answer flagging

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1118]
It would be nice to have an option for flagging text answers during the review process. Staff users and reviewers should then have the possibility to display all flagged text answers of a semester in a new view. Flags won't influence anything else, especially approving text answers is independent.

**Comment by pixunil** [comment]
Some ~80% code here: https://github.com/pixunil/EvaP/tree/textanswer-flagging

**Comment by janno42** [comment]
An additional requirement came up a few days ago: In quick text answer review, evaluations, where all remaining unreviewed text answers are flagged, should not be suggested as the following evaluation for review.

**Comment by BenBals** [comment]
We just discussed our review workflow on at a FSR meeting. We currently use the skip feature for exactly that reason. But flagging, especially with a unified list/view across evaluations, would be a much better solution.
