### ISSUE TITLE
Appending/editing text answers after submitting votes

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1132]
Students should be able to submit additional text answers or edit already submitted answers even after they submitted their votes for a course if the course is still in evaluation. They can then reopen the voting page where all rating questions are disabled, only text questions are available.
New text answers will be added like the original ones.

For review purposes (to prevent one user spamming the same answer over and over) text answers need to be grouped by user (see #1130).

**Comment by karyon** [comment]
To clarify: Appending new answers already requires the grouping feature for abuse prevention. Thus we can, without reducing anonymity even further, fetch all answers of a user from the database and display them, allowing the user to edit them.

**Comment by janno42** [comment]
Closed, see #1130
