### ISSUE TITLE
Keyboard controls for voting

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1134]
voting should be easily possible using only the keyboard and without using the tab key too much :)

either use the same approach as in #1094 (show one question at a time, some key advances to the next question) or, alternatively, leave the page design unchanged but have one question focused, use the keys to answer, and then move the focus to the next answer.

**Comment by pixunil** [comment]
I think the usage of a quick view and a full view like for #1094 fits very well to improve experience on mobile devices as for #883.
