### ISSUE TITLE
Importing a backup made by update_production.sh does not work flawlessly.

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1240]
Last week we wanted to do a production update. The json dump file created during that update could not be imported without issues:
- The dump does not contain the cronjob user, but foreign key references to it. This can not be imported
- The dump contains data included by django by default (auth, permission, ...). These need to be excluded when importing.

There should be some kind of documentation on what needs to be executed to import this dump back into the database. We should also add some test (could probably just run on travis) that ensures this always works (dump, flush database, migrate, load dump).

**Comment by karyon** [comment]
we have `dump_testdata`, which probably dumps the data we want to dump in `update_production.sh`. maybe we should make `dump_testdata` take an `output` parameter which is forwarded to `dumpdata`, and if it's not specified, it's set to the `outfile_name` variable that's created there. then we can use `dump_testdata` in `update_production.sh`.

**Comment by He3lixxx** [comment]
In #1353 we messed up the directories - on production, the repo is located somewhere else.

Also, in #1353, I forgot to change the apache2 config file templates. They still point to the old vagrant home directory, so apache2 inside the vagrant vm doesn't work.
