### ISSUE TITLE
Use consistent Email forms

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1284]
We're currently using different forms for editing emails. `EvaluationEmailForm`, `EmailTemplateForm`, and a form in `staff_evaluation_operation.html`.
We could think about using a standardized form in all places.

**Comment by He3lixxx** [comment]
My main issue with using one standardized form is that we would have to abuse
- either a non-model-form for modifying a model, which would make us write all the validity-checks on our own. For example, max title length - we wouldn't want to check that ourselves, would we? If we had a custom form that just changes an EmailTemplate instance, setting `title` to a string that is too long and calling `save` would lead to a 500 afaik
- or a model-form for editing something that is not actually a model. I don't see how this would be less weird in the end. What if the model gets additional fields? Also, we don't want to change any database instances.

Overall, I don't see any non-weird ways to combine these.

**Comment by He3lixxx** [comment]
For quicker access to the three forms:
- http://localhost:8000/staff/semester/21/evaluation/1499/email
- http://localhost:8000/staff/template/2
- http://localhost:8000/staff/semester/21/evaluationoperation?evaluation=1614&target_state=in_evaluation
