### ISSUE TITLE
Refactor Evaluation state transition names

### ISSUE THREAD

**Issue by felixrindt** [e-valuation/EvaP#1331]
As a followup to #1310, we became aware that the evaluation state transition function's names aren't quite consistent along themselves. Also, naming could be improved throughout the whole project. For example from #1310, there is a name mismatch with

* `MoveToPreparedOperation` and `evaluation.ready_for_editors`
* `StartEvaluationOperation` and `evaluation.evaluation_begin`
* `RevertToReviewedOperation` and `evaluation.unpublish`

**Comment by karyon** [comment]
I would also propose `evaluation_begin` ->`begin_evaluation` (or `start_evaluation`), also `evaluation_end` -> `end_evaluation`.

I also thought about `review_finished`. While it accurately describes what has happened for the transition to occur, I think it should rather describe the transition itself. so `finish_review` might be better, or actually I don't see any reason to not call it `end_review` to be in line with `end_evaluation`.
