### ISSUE TITLE
Redesign user index

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1333]
The user index page loads quite slowly. This could probably be improved be removing badges that are not really needed ("Contributor", "Responsible", "External", "No email") and postponing the `can_be_deleted_by_manager` check to be run only after clicking the button and returning an error message if not possible
It should be investigated if further improvements to the loading time are possible.

**Comment by karyon** [comment]
In an offline discussion, @janno42 realized that the delete button could simply be moved to the user edit form.

**Comment by janno42** [comment]
In most cases we don't need a complete list of all users at all. So the user index page should be changed to an overview page like the staff index giving access to:
- user import
- user adding
- user merge
- user bulk update
- the complete user list as it is now but extended by filters for proxy users, managers, grade publishers, and reviewers
- a new search field where all users (including inactive and proxy users) can be found via a user selection field which then allows to open the respective user's edit form for a specific user

**Comment by karyon** [comment]
to avoid any confusion, you want to *keep* the full list but extend it with more filters, and add buttons to import/merge etc at the top?

and your last bullet point I didn't understand. What does it do differently than the current search field?

**Comment by janno42** [comment]
the full list with additional filters is for the rare cases where you might want to see all reviewers when the student representative group changes or something like that. but it needs to be an extra page instead of the index, so that for all other use cases the loading time of the list doesn't matter anymore.

the search field should be placed on the (new) user index page and could work just like the contributor selection fields but with a button next to it opening the selected profile.

**Comment by karyon** [comment]
ooooh i see. So it's a completely new page with a button leading to the old one.

i would suggest leaving out the additional filters to the old page for the first PR to make this issue more accessible. maybe add the delete button to the user edit form instead, so the new page can cover more use cases. maybe the old page really becomes irrelevant then (or irrelevant enough that typing 'reviewer' into the search field is sufficient for your "see all reviewers" use case)

**Comment by janno42** [comment]
ah right, i had searching like that in mind and somehow forgot it on the way writing the requirement above. you are right: additional filters are not required. i'll update the list above and add the delete button thing.

**Comment by janno42** [comment]
@lill28 do you still want to work on this issue?
