### ISSUE TITLE
Make emails main identification for users

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1374]
After the change to OpenID for the login we rarely require the usernames anymore. Therefore we should make emails the main identification for users.

That means:

- [x] The importers shouldn't expect username columns anymore.
- [x] User selection fields should show the leading part of the email address (everything before the `@`) instead of the username.
- [x] The user profile UI needs to be updated in several places.
- [x] ~User merging must be updated.~ (nothing to do right now)
- [x] User bulk deletion must be updated.
- [x] The development login option with username and password should be changed to email and password (where we could allow invalid email addresses, so that `evap` would stay a valid login name).

After this the username can completely be removed from the `UserProfile`.

**Comment by felixrindt** [comment]
This might lead to a lot of hickups because of the `@hpi.de` and `@hpi.uni-potsdam.de` identity.

**Comment by janno42** [comment]
That's no problem, we're already replacing these on saving. So all addresses have the same domain.
