### ISSUE TITLE
Move grading attribute into Evaluation

### ISSUE THREAD

**Issue by felixrindt** [e-valuation/EvaP#1379]
When I have an unpublished, reviewd midterm evaluation, I would expect to get the red "results could probably be published" tag. At the moment, it's just the yellow one.
![image](https://user-images.githubusercontent.com/5970076/69233266-e85da680-0b8c-11ea-9233-37ec202e6252.png)

For example in line 

https://github.com/fsr-de/EvaP/blob/6a42001e8cb5365890c025e79983a4ea31f25bb6/evap/results/templates/results_index_evaluation.html#L42

also midterm evaluations should be allowed.

**Comment by janno42** [comment]
The required change is not quite that simple. For ungraded courses the red icon is already shown, so that's no problem.
But for graded courses we might want to wait for grades even in case of midterm evaluations - e.g., when it is an evaluation for a midterm exam.
So to change this we would have to introduce an additional flag on evaluation level stating whether this evaluation has to wait for published grades in addition to the current `is_graded` on course level.

**Comment by janno42** [comment]
We don't use `Course.is_graded` for anything besides deciding whether to wait for grade uploading before publishing results.
So we can move this information into a new attribute `Evaluation.wait_for_grade_upload_before_publishing` that will be `True` by default and replaces the current Course attribute.
Badges, icons and when evaluation results are published have to be updated accordingly.

**Comment by meisterl-max** [comment]
@janno42 when importing files, should there be a seperate column for the attribute Evaluation.wait_for_grade_upload_before_publishing or should it always be set to default?

**Comment by meisterl-max** [comment]
@janno42 actually, course.is_graded is being used in grades_semester_view.html. With the new attribute, should we filter courses that have at least one evaluation with wait_for_grade_upload_before_publishing?

also, should the course still get a badge if its evaluations are wait_for_grade_upload_before_publishing?

**Comment by janno42** [comment]
The column in the importer should stay (so replace the current `is_graded` for the course with `wait_for_grade_upload_before_publishing` for the evaluation.).
The badge from the courses should move to the evaluations.
And yes, please show only courses in grades_semester_view when they have at least one evaluation that is waiting for grades.
