### ISSUE TITLE
Upgrade to django 3.0

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1387]
https://docs.djangoproject.com/en/3.0/releases/3.0/

There is a guide for upgrading: https://docs.djangoproject.com/en/3.0/howto/upgrade-version/

Basically
* Read the release notes
* check dependencies for compatibility and update those
* run tests with `python -Wa` and solve deprecation warnings
  * Be aware of #1359
* put the new django into the requirements
* run tests, fix failures if any
* run tests with `python -Wa` and solve deprecation warnings again
* if there was any new feature in the release notes that might help us, use it
  * I spotted [Enumerations for model field choices](https://docs.djangoproject.com/en/3.0/releases/3.0/#enumerations-for-model-field-choices), anything else?

also, we need to check the installed python version on production, django 3.0 supports python 3.6 and newer. I think right now production runs python 3.5.

**Comment by janno42** [comment]
It's still 3.7 ;)
