### ISSUE TITLE
Redesign import

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1389]
When importing data, the import should only be done after an explicit confirmation in a modal (similar to the confirmation when approving evaluations).
The process then would be:
- Upload file for testing
- Resolving errors if needed and re-upload for testing
- Click on "Import previously uploaded file"
- Confirm in a modal

In addition, the colors of the buttons should be changed: The import button should stay `btn-primary` and the test button should always be a `btn-light`.

This should be done for the enrollment import, the user import, and on the Courses' person management pages.

**Comment by janno42** [comment]
@ScrappyDieRaupe do you still want to work on this?

**Comment by ScrappyDieRaupe** [comment]
Yes, but it might take some time as I'm not actively working on it right now. If it needs to be done quickly, feel free to unassign me.
