### ISSUE TITLE
Logging changes for Courses and Evaluations

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1401]
When making changes in Courses and Evaluations, these should be logged. This should be the case for all users who can make changes (editors and managers) and should include status changes as well as changed fields with timestamp and user.
The log should be accessible on the manager's edit page.
See also #1348.

**Comment by felixrindt** [comment]
I think I want to work on this. I liked the generic way this is done [at pretix](https://github.com/pretix/pretix/blob/master/src/pretix/base/models/log.py) - although we probably not need such an elaborate structure using arbitrary model references and signals for pluggable event types.

They have this as a column on the right next to the main content element, here for a "Termin"-Model of an event:

![image](https://user-images.githubusercontent.com/5970076/71834380-629ba900-30af-11ea-8ed9-7f31e251201a.png)

**Comment by janno42** [comment]
Besides changed fields in general, the log information for questionnaire changes must include the specific questionnaires that have been additionally selected or deselected.

**Comment by felixrindt** [comment]
I started to work on this. Looking promising already.

![image](https://user-images.githubusercontent.com/5970076/73694694-e067ca00-46d8-11ea-8c19-14c1154a6ceb.png)

A lot of logic will probably go into displaying the diff nicely and meaningful for all the different types of attributes. Here's a broad overview:

* [x] Create LogEntry Model
    * [x] log and meaningfully display plain attributes
    * [ ] log and meaningfully display one-to-many changes
    * [ ] log and meaningfully display many-to-many changes
* [x] Make Evaluation a logged Model
    * [x] pass user from staff views
    * [ ] pass user from responsible views
* [ ] Make Course a Logged Model
    * [ ] pass user from staff views
    * [ ] pass user from responsible views
* [ ] Remove `last_modified_user` and such

**Comment by felixrindt** [comment]
I think we could also be logging changes to user profiles, as that might be relevant for audits.
