### ISSUE TITLE
Locked questionnaires

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1418]
There should be an option for managers to lock a questionnaire. This will then prevent editors from adding or removing this questionnaire, while they are still able to see it in the list (depending on its visibility setting).

This setting should be done for each questionnaire globally, similar to the visibility setting. If locked, the specific questionnaire field in the evaluation and contribution forms should be deactivated for editors.

**Comment by PFischbeck** [comment]
While working on this, I noticed a problem with locked contributor questionnaires. Does it even make sense to lock them? What should happen if a contributor questionnaire is locked to "yes, always include this"? Can one still select "Does not contribute"?
