### ISSUE TITLE
Auto-save information

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1426]
Answers in the student vote form are auto-saved locally. There is a button that can be clicked for manually saving locally but it is more or less useless, because the save is already done automatically on every form change.
Users wanted an "easier auto-save" by using hotkeys - we should instead show the information about the automatic saves in a more detailed way and remove the button for saving manually.

A small info text like `Last auto-save in browser: <Timestamp>` should be displayed instead, giving more details about the continuous saving. Info that the evaluation can be continued another time when using the same browser on the same device should be placed in a tooltip.

**Comment by felixrindt** [comment]
I'd like something human for the timestamp like "3 seconds ago", similar to django's [humanize](https://docs.djangoproject.com/en/3.0/ref/contrib/humanize/#naturaltime).

**Comment by janno42** [comment]
@ScrappyDieRaupe do you still want to work on this?

**Comment by ScrappyDieRaupe** [comment]
Feel free to unassign me if it needs to be done quickly. 
I might work on this some time in the future.
