### ISSUE TITLE
OpenID login button is broken in latest firefox

### ISSUE THREAD

**Issue by ADimeo** [e-valuation/EvaP#1466]
Behavior:
When clicking the "login" button at `https://evap.hpi.de` a request is sent to `https://evap.hpi.de/oidc/authenticate/`, which returns a 302 and redirects to `https://evap.hpi.de/?next=/oidc/authenticate/`, which has no visible difference with `https://evap.hpi.de`. After clicking the login button again I'm redirected to `https://evap.hpi.de/?next=/oidc/authenticate/%3Fnext%3D/oidc/authenticate/`

Expected Behavior:
Display the openID page and allow login

Steps to reproduce
Go to https://evap.hpi.de and click the "login" button. Browser is an up-to-date firefox on linux

**Comment by He3lixxx** [comment]
Thank you for reporting this!
