### ISSUE TITLE
test_results_cache_refreshed is acting weird

### ISSUE THREAD

**Issue by niklasmohrin** [e-valuation/EvaP#1486]
`test_results_cache` in `staff/tests/test_forms.py` is failing randomly.

Behaviour observed:
- On master, without `--keepdb`, it seems to pass most of the time (not one crash in about 15 runs in a row)
- It broke three out of eight times on master with `--keepdb`
- On one of my branches (the Exporter refactor), it breaks on every 2nd - 5th test run (with `--keepdb`)
- It broke once for @He3lixxx over the period of the entire evening

My master was at `4595866ed29b3209cfeb66994aa347ec9a66e1e0`

**Comment by niklasmohrin** [comment]
Update: it just broke without the `--keepdb` flag (on a feature branch though)

**Comment by He3lixxx** [comment]
```
======================================================================
ERROR: test_results_cache_refreshed (evap.staff.tests.test_forms.UserFormTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/evap/evap/staff/tests/test_forms.py", line 146, in test_results_cache_refreshed
    results_before.contribution_results[0].contributor.first_name,
AttributeError: 'NoneType' object has no attribute 'first_name'

----------------------------------------------------------------------
Ran 411 tests in 54.675s
```

So usually, collect results has two contributors for `results_before.contribition_results`, which are `[<UserProfile: <unnamed> (User 63)>, None]`. Sometimes, the order is switched here, and so `contribution_results[0].contributor` is None.

Afaik, we don't want `collect_results` to return these results in any specific order, right @janno42 or @karyon (`_collect_results_impl` does not do any ordering or sorting), so this is a bug in the test, not in the actual code. Quite funny that the ordering worked out most of the time.

**Comment by janno42** [comment]
as the general contribution is handled independently in most cases, we probably never thought about a specific ordering there. contributions do have an order field but i guess its value for the general contribution is not consistently handled with the other contributions?
however, i don't think that we need to change how collect_results handles the ordering.
