### ISSUE TITLE
Questionnaire names in result exports

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1487]
When hiding a questionnaire and creating a new version, the current date will be added to the title of the old questionnaire. This information will be shown in exports which might confuse users. We should think about only showing the display name instead or handling it in a completely different way. We have to think about exports where multiple old questionnaires of the same name are included though.

**Comment by janno42** [comment]
The questionnaire's display name should be used in exports for hidden questionnaires (which are usually "archived" and not actively used anymore). In case there are multiple questionnaires with the same display name, `(archived questionnaire)` should be added behind the name.

**Comment by dieknolle3333** [comment]
I find it hard to reproduce the issue: If I hide and create a used questionnaire and then export it in the staff view via "Export results", the export only shows the display name (without the date) of the old questionnaire. What am I missing?
