### ISSUE TITLE
Configurable text answer warnings

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1507]
There currently exists a text answer warning when students use terms that might reference the answer to a different question (`doesTextareaContainReference` in `student_vote.html`).
Similarly, such warnings could be used for strong language and other use cases.
The current warning should be changed to a customizable system where staff users can define any number of warnings on a new ui page and define a list of triggering strings for each warning.

The warning for meaningless text (`isTextareaInvalid`) can stay hard-coded but should probably be renamed to something like `doesTextareaContainMeaninglessText`.

**Comment by karyon** [comment]
The FAQ entry form might be a good template for this.

Why not treat the meaningless text warning just as any other? It could be added in a data migration.

The warning shown to the user should be in german and english, i suppose?

**Comment by janno42** [comment]
Yes, I had something like the FAQ page in mind and the warnings should be both German and English.
The meaningless text works a bit different from the others as it won't be triggered after a certain number of relevant characters was entered.
