### ISSUE TITLE
Filtering evaluation results doesn't work in Firefox

### ISSUE THREAD

**Issue by strawberriesandcheese** [e-valuation/EvaP#1516]
I wanted to look up evaluation results from some of my courses using Firefox. 
I wanted to filter for a specific semester, degree and type of course. 

Even though I clicked on the filters and the checkmarks appeared nothing changed about the courses displayed below, even though some of them were MA-ITSE courses while the filter was set to BA-ITSE. I expected that the courses not matching my checkmarked filters would disappear.

Additionally no filters were selected initially which is at least different from the behaviour EvaP shows under Chrome. I would expect similiar behaviour in all tested browsers but I suspect this discrepancy could be rooted in the same bug as the behaviour described above.

**Comment by He3lixxx** [comment]
Works for me in Firefox 81.0.1 on Windows.

The filtering is done with javascript on the client side. Do you have any privacy / javascript filter addons that might interfere? If I block javascript execution with uMatrix, I get the behavior you described.

**Comment by janno42** [comment]
the problem was a very old firefox version, after updating everything works as expected.
