### ISSUE TITLE
Attached text answer fields for rating questions

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1542]
Rating questions should get an attached text answer field that allows an additional text answer to be submitted for that rating question. The text answer field should be hidden and only be shown after clicking on a button/dropdown arrow/etc.
By default, every rating question should have this additional text answer field, but this must be configurable for each question in a questionnaire.

This is meant to be used in situations like a rating question stating a contributor "showed respect for the participants" and a participant wanting to add a specific comment to this situation. Having the text answer fields hidden does not increase the number of questions a participant feels pushed to answer while still giving the opportunity for additional specific feedback if required.

**Comment by karyon** [comment]
PO casually overturning several major design assumptions the code is based on :D

But I like the feature.

**Comment by janno42** [comment]
Should I add the `Big` label? 😁

**Comment by karyon** [comment]
I dunno, we should probably do some UI and architecture design work first. It might be not as bad as I first thought :)
