### ISSUE TITLE
Feature Request: Allow students to collect notes for evaluation already while a course is running

### ISSUE THREAD

**Issue by LinqLover** [e-valuation/EvaP#1566]
As a student, I often notice a few aspects of a course a long time before the evaluation is opened. I see that it would be a bad idea to open evaluations much earlier since people could submit them without taking the entire duration of the course into consideration, but I would love an option to open all evaluations as the course begins in a kind of **draft mode** which already would allow me to take notes and collect some thoughts so I do not forget them again before the eventual evaluation period starts.

**Comment by He3lixxx** [comment]
Related: https://github.com/e-valuation/EvaP/issues/1041

**Comment by janno42** [comment]
as discussed in the above-linked pr, we won't implement this now.
but there will be future internal discussions about options to take notes.
