### ISSUE TITLE
Filter evaluations on fast review

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1572]
When finishing the review of an evaluation's text answers in fast mode, only evaluations where the evaluation period already ended should be selected for continuing the review. Currently, also evaluations that are still in evaluation are shown.

**Comment by karyon** [comment]
why? :)

**Comment by janno42** [comment]
Running evaluations are usually not to be reviewed to ensure the review of all text answers in an evaluation is done as a whole. This gives the evaluation team a complete overview of the course, which can be summarized for reports and feedback discussions.
If staff wants to review a specific evaluation after the change anyway, they can still open the review for this evaluation.
