### ISSUE TITLE
Import data test improvements

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1574]
Importing enrollment data often is a tedious process and should be assisted as far as possible. Some potential problems in the data are currently not checked by the importer, and others generate a large number of warnings for the same problem.

These are changes that should be made to the testing phase of importing enrollment data:
- If the study degrees of a course do not match in all lines of the import file, only one warning should be shown, listing all study degrees found for the course.
- If a user has different study degrees in one import file, this should be shown as an error.
- A new warning section, "Similar course names", should be added. This should be filled with warnings for all pairs of course names with a small string distance. Examples are typos, where cases change, or a small number of letters are missing, changed, or added.

**Comment by He3lixxx** [comment]
Regarding degrees:
* We change it so that only a single degree can be provided for one enrollment (i.e. the "degree of the user"). This removes the need for point 1 from the issue description.
* We add a check that the degree is identical in all enrollment rows of a single user. This solves point 2.


Point 3 remains as described above.

**Comment by niklasmohrin** [comment]
Dependency seems appropriate; the triangle inequality should hold for edit distance, so maybe we can use something fancy to avoid n^2 runtime? I was first thinking about that TI exercise about closest-points-problem, but that uses metric space stuff; maybe k-neighbours kind of stuff is better? or we just take the n^2 :D
