### ISSUE TITLE
Import enrollment data with existing courses

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1596]
When importing enrollments, it currently is not possible to import data with courses that already exist in the semester.
Instead,
- if all attributes of the course (names, type, responsible person, graded) match with the existing one and
- just one evaluation exists for this course,

the importer should show a warning and
- add all new participants from the enrollment data to the existing evaluation and
- add degrees to the course if necessary.

**Comment by janno42** [comment]
@jb3rndt do you want to continue working on this?

**Comment by jb3rndt** [comment]
Yeah I would like to :)

**Comment by niklasmohrin** [comment]
Fixed in #1683
