### ISSUE TITLE
Button "Create evaluation" visible for reviewers

### ISSUE THREAD

**Issue by jeriox** [e-valuation/EvaP#1606]
As a reviewer viewing the overview of a semester, the list shows buttons to "create evaluation" and "create single result".
When clicking the button, the system presents me with an error view because I don't have the appropriate permissions.
I expect the system to only show me buttons for the actions that I have permissions for.

**Comment by janno42** [comment]
The same is true for the `courses` tab, where the buttons for creating evaluations and single results should only be shown for managers.
