### ISSUE TITLE
Single results' results are hidden in course detail page if not published

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1621]
If a single result is shown on a course detail page of another evaluation of the same course, its results are hidden if it's not yet published. Non-published regular evaluations have their results shown, just as all published evaluations do.

The fix is simple, but I wanted to make sure this behavior is not expected...? It seemed inconsistent to me. 

See screenshot. Note how Bar's results are not shown, but "Software Architecture" and "Bar2" have their results shown.

![image](https://user-images.githubusercontent.com/1891915/131266243-2494d449-db7c-4146-ab35-e77d77f25bf7.png)

**Comment by janno42** [comment]
Nice, this indeed is an inconsistency that should be fixed.

On another matter: The weighting percentages in the screenshot seem broken, shouldn't they add up to 100%?

**Comment by karyon** [comment]
yes!
