### ISSUE TITLE
Jumping form on submit

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1638]
When having the cursor in the participant field in an evaluation form and clicking on "Save" on the bottom of the page, the form jumps back to the participant field (now not having the focus anymore). When clicking "Save" again, the form is saved.

The form should be saved when clicking "Save" for the first time, the form should not jump back to the participant field.

**Comment by dieknolle3333** [comment]
This seems to be an issue in select2: https://output.jsbin.com/cosocudiqe.
I opened an issue in their repo regarding this.

**Comment by janno42** [comment]
will be handled in #1461
