### ISSUE TITLE
Pylint didn't complain about unused variable

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1641]
We had a variable that was found to be unused in a manual review and should investigate why pylint didn't find it.

```
Just read the comment and thought: Why does pylint not give an error? It should fail when unused variables are assigned and they are not called `_` or `__`.
```
_Originally posted by @He3lixxx in https://github.com/e-valuation/EvaP/pull/1632#discussion_r725975337_

**Comment by He3lixxx** [comment]
I opened an issue with pylint at https://github.com/PyCQA/pylint/issues/5838

**Comment by He3lixxx** [comment]
Closing for now, upstream issue is open, so there's no more stuff to do for us.
