### ISSUE TITLE
Consider replacing Select2 with Tom Select

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1672]
We should investigate whether it's worth to replace Select2 with Tom Select (https://tom-select.js.org/).
It looks like it would make several things easier. We need to find out if it fulfills our current use cases, maybe obsoletes some issues in #1461 and possibly makes formatting for special use cases (like having just one user per line as requested in #1569) easier.

**Comment by janno42** [comment]
In general, Tom Select seems suitable as a replacement for Select2.
Multi select fields could be initialized like this:
```
applyTomSelectMultiple = function(elem, parent = $(document.body)) {
    var config = {
        placeholder: "{% trans 'Please select...' %}",
        hidePlaceholder: true,
        plugins: {
            remove_button: {
                title: "{% trans 'Remove this item' %}"
            },
            clear_button: {
                title: "{% trans 'Remove all items' %}"
            }
        }
    };
    elem.each(function() {
        new TomSelect($(this), config);
    });
};
```
The two plugins are not needed for single select fields.

At least one thing still needs investigation: In user selection fields we don't want to show suggestions before at least 3 characters were entered (because earlier suggestions don't make sense and we don't want to show the always same users that are first in the list, when editing any user selection field). There is no simple configuration option for that so we would have to implement it on our own.

**Comment by He3lixxx** [comment]
Our current implementation for minimum input length: `templates/base.html` sets `minimumInputLength` to 3 if more than 50 options are available.

The TomSelect documentation lists the `shouldLoad(query)` configuration parameter as a solution to accomplish this:
> Use the `shouldLoad()` callback to implement minimum input length or other input validation. If the callback returns false, `load()` will not be called and the `not_loading` template will be added to the dropdown instead of the `loading` or `no_results` templates.

Seems pretty straightforward to do a simply `return query.length > 3;`

**Comment by He3lixxx** [comment]
A bit of a bumper: tomselect has builtin bootstrap5 support (good), but this expects that we adhere to the documentation.
Currently, we use the `is-invalid` on parents of the input that is actually invalid, e.g. in evap/evaluation/templates/bootstrap_form_field_widget.html. This doesn't match what I think the [bootstrap documentation](https://getbootstrap.com/docs/5.0/forms/validation/#server-side) allows us to do.

Tomselect assumes that the class will only be set for the select-element, not the div around it, so now it renders its error icon at a wrong location:
<img height="150" src="https://user-images.githubusercontent.com/13838962/168159693-24c0925d-8418-46dc-b950-23468b0182fb.png"></img>

We could hotfix that in javascript for tomselect, but in the end, I thinkt we might be better off by actually setting `is-invalid` on the input/select element. However, that doesn't seem to be too easy at the moment.
