### ISSUE TITLE
Evaluation weight doesn't add up to 100%

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1691]
Split out from #1621. See screenshot:
![image](https://user-images.githubusercontent.com/1891915/147852750-2dd6c5c2-a500-42a1-b997-ec2e74039da8.png)

**Comment by karyon** [comment]
@janno42 if there's an evaluation with some non-zero weight that's not shown (evaluation hasn't started yet for staff users, evaluation is not published for all other users), should the shown weights still add up to 100% or to 100% minus the percentage of the hidden evaluation? what if the evaluation is shown here but the grade (and thus the percentage) is not shown?

**Comment by janno42** [comment]
The percentage values should reflect the total weighting (from a global permission-independent view) even if single evaluations are not shown. So the values may add up to less than 100%.
If an evaluation is shown but the grade is not yet displayed, we should optimally already show the percentage.

**Comment by karyon** [comment]
The problem is that [this annotate](https://github.com/e-valuation/EvaP/blob/1427e47d4eddec45d443bc441d61d4298219dbd8/evap/results/tools.py#L301) operates on the filtered evaluations. Swapping the filter and the annotate should work [according to the docs](https://docs.djangoproject.com/en/4.0/topics/db/aggregation/#order-of-annotate-and-filter-clauses), but it gives me the sum multiplied by the number of evaluations per course. This might be a variant of [this documented bug](https://docs.djangoproject.com/en/2.2/topics/db/aggregation/#combining-multiple-aggregations). Fetching the courses separately like below would work, but maybe there's a better approach.

```python
    courses = Course.objects.filter(evaluations__in=evaluations).values_list("id", flat=True)

    course_id_evaluation_weight_sum_pairs = (
        Course.objects
        .filter(pk__in=courses)
        .annotate(Sum("evaluations__weight"))
        .values_list("id", "evaluations__weight__sum")
    ) 
```

An additional weirdness of this view is that first the correct value is annotated [here](https://github.com/e-valuation/EvaP/blob/1427e47d4eddec45d443bc441d61d4298219dbd8/evap/results/views.py#L195) (it is correct because the list of evaluations contains all evaluations of the course), but then overwritten with an incorrect annotation [here](https://github.com/e-valuation/EvaP/blob/1427e47d4eddec45d443bc441d61d4298219dbd8/evap/results/views.py#L210).

**Comment by He3lixxx** [comment]
Generally, the filter-then-annotate approach in results/views.py:210 is wrong, so I think fixing that method in itself is an okay solution for this issue.

Analyzing why the annotation happens twice is maybe something for another issue.
