### ISSUE TITLE
Allow anonymous feedback messages via settings

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1704]
When sending a message in the feedback form, the sender field is currently automatically filled and disabled; thus users cannot give anonymous feedback.
This should be made optional via a new setting `ALLOW_ANONYMOUS_FEEDBACK_MESSAGES`. When set to `FALSE`, the current behavior is kept. When set to `TRUE`, a new checkbox is shown in the form, enabling users to send their message anonymously. Checking this checkbox will remove the sender information in the form and in the sent message's text.

**Comment by He3lixxx** [comment]
@janno42 How much consideration went into the "checkbox" design already? The modal already has a disabled "Sender" field, I would have expected that this simply gets enabled and users get to choose between their name and "anonymous message"

**Comment by janno42** [comment]
i initially thought of a checkbox that would remove the sender field like when deselecting "send message" on starting evaluations etc.
but using a button switch with the two options "send as <name>" and " send anonymously" sounds good.
