### ISSUE TITLE
Delete answers for questionnaires removed from evaluations

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1717]
Staff users can remove questionnaires from running or finished evaluations so that the contained questions will not be shown to voters participating in the evaluation from that point on. However, answers that have already been given for these questions before the questionnaire was removed, remain in the database. This leads to inaccessible text answers, blocking the review process.

It is necessary for staff users to be able to remove questionnaires in case they have been selected by mistake and are not applicable for the evaluation. So all answers for these questions need to be deleted when removing the questionnaires.
In addition, questionnaires for which answers have already been recorded should be highlighted in the evaluation form with an accompanying warning that answers for these will be deleted if the questionnaires are removed.
This applies to general questions as well as contributor questions.

**Comment by niklasmohrin** [comment]
This issue is identical to #1716, but has a different priority :thinking:

**Comment by janno42** [comment]
oh nice. github decided to not process my issue creation before and somewhere on the way this mess seems to have happened ...
