### ISSUE TITLE
Codecov: Uploader deprecated, wrong assignment of coverage information to code lines.

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1723]
### Codecov uploader deprecated, switch to github action?
The pacakge `codecov`, [which we use](https://github.com/e-valuation/EvaP/blob/main/requirements-dev.txt#L3), is [deprecated and not supported anymore](https://github.com/codecov/codecov-python), so we have to update our github workload there. Probably, the [github action they provide](https://github.com/marketplace/actions/codecov) will do the job. Maybe, this would already fix the issue mentioned below

### Wrong attribution of coverage information to code lines
Noticed in #1667, where miraculously we suddenly achieved 100% test coverage on the diff, then though a view clearly was never tested.

The github checkout action we use: https://github.com/e-valuation/EvaP/blob/cb518fcab747b44983a7924c8bbfd8d8cca97070/.github/workflows/tests.yml#L38-L39

checks out a [merge result of that PR into the current main](https://github.com/e-valuation/EvaP/runs/5561489764?check_suite_focus=true#step:3:474).

(Note: This can be [changed to instead checkout the HEAD of the PR](https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit), but I really think we shouldn't)

However, the [codecov uploader reports the coverage for the HEAD commit instead of the merge commit](https://github.com/e-valuation/EvaP/runs/5561489764?check_suite_focus=true#step:6:32). So, codecov assumes the coverage measurement was done on the pull requests HEAD.

A coverage report is an XML document with the semantical information like "evap/staff/views.py, line 1234: covered once", so this leads to a wrong attribution of covered and missed lines if line numbers changed during the merge. For example, [the annotation on this line](https://app.codecov.io/gh/e-valuation/EvaP/compare/1667/changes#D4L1947) should actually go on [this statement 44 lines earlier](https://app.codecov.io/gh/e-valuation/EvaP/compare/1667/changes#D4L1903)

**Comment by He3lixxx** [comment]
#1746 touches the action anyways, so I decided to also directly switch to the new codecov action. We will have to see whether that fixes it.

**Comment by He3lixxx** [comment]
On https://github.com/e-valuation/EvaP/pull/1756, codecov reported absurd numbers again (+0,36% coverage, although no line coverage was changed), even though the branch was already completely up to date.

**Comment by Kakadus** [comment]
https://github.com/e-valuation/EvaP/runs/7405633628

**Comment by He3lixxx** [comment]
> https://github.com/e-valuation/EvaP/runs/7405633628 shows project diff of -0.02%

Since we could not really figure out what's going on there (and thus neither confirm that the original issue described here happened, i.e. coverage being attributed to wrong lines due to the coverage being reported for the wrong commit), I'm closing this for now.

Feel free to reopen if the issue described in the original post happens again somewhere.
