### ISSUE TITLE
Update "last saved" counter less frequently

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1741]
The counter on the student vote page showing when answers were last saved locally is currently updating every second (for the first three seconds it displays "just now"). We received feedback that the value changing every second induces stress for some users.

The reason for having the counter is to show users that their answers are automatically saved whenever they are changing anything. So it is not really necessary to update the counter every second, as long as it is updated as soon as answers have been changed.

Thus, the counter should be changed as follows: When the last change was less than ___ seconds ago, it should show the message ___:
- 3: just now
- 10: less than 10 seconds ago
- 30: less than 30 seconds ago
- 60: less than 1 minute ago
- and after that, as is

**Comment by He3lixxx** [comment]
solved in #1752
