### ISSUE TITLE
Staff vote preview page is accessible, but crashes when no questionnaires are assigned

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1747]
We currently have this situation with http://localhost/staff/semester/21/evaluation/1668/preview. There are two contributions for this evaluation, but no questionnaires are assigned.

The staff `evaluation_preview` view calls `get_valid_form_groups_or_render_vote_page`, which in turn will check whether all form groups are valid -- there are no form groups, so this is the case. The method then asserts `not preview`, which fails.

The preview button on the staff semester view that leads to this page is enabled (it is shown if `evaluation.state < evaluation.State.IN_EVALUATION`).

@janno42 how to we want to handle evaluations without any assigned questionnaires, regarding preview as well as starting the evaluation. From what I see, starting an evaluation that has no questionnaires assigned is currently possible?

**Comment by janno42** [comment]
Approving an evaluation without questionnaires is not possible via the frontend, so an evaluation without questionnaires cannot be started.
The preview in this case should probably simply show an empty voting page.
