### ISSUE TITLE
Add notebook

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1760]
Users should have a place to take notes on EvaP. For example students could use this to save text during the semester which they want to use in later evaluations or which they can use as a reminder about what they wanted to write.
For these notes, a plain text area should be provided. It might be extended with formatting and other features in the future, but this is not in scope of this issue.
The entered text should be saved connected to the user's profile on the server and thus be available on any device the user logs into the platform (a corresponding information about anonymity must be shown).

----
A first design study can be found in 4366a2a07dc1. This is not a complete frontend implementation and many details are still open for discussion.

Floating button to open the notebook:
![image](https://user-images.githubusercontent.com/1781719/168350996-8ed8f8bd-96d6-4710-b6c1-5ba9c35e5e35.png)

The notebook itself in a Bootstrap Offcanvas:
![image](https://user-images.githubusercontent.com/1781719/168351498-b183a149-1501-481c-b6cb-6a86c461e652.png)

**Comment by fidoriel** [comment]
I would take it.

**Comment by karyon** [comment]
Previous discussion: #1041, and a duplicate: #1566

**Comment by janno42** [comment]
We could probably remove the backdrop and not auto-close the offcanvas when clicking somewhere else. If you have additional ideas that work with the existing page or do not make things too complicated, let me know!

This is meant to be a low-level approach for unstructured note-taking that shouldn't add too much complexity. As such, it's not really a duplicate of the above-mentioned issues, there we had more in mind and several of the ideas are still out of scope.

**Comment by fidoriel** [comment]
I would throw in my approach to the issue. It is buggy, but I think you will get the pioint: [https://github.com/fidoriel/EvaP/commit/6826ea735e7f842dd7a65528bd8f5c9428fa458b](url)
