### ISSUE TITLE
Customizable Infotext

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1768]
On the student index page and the contributor index page we currently show hardcoded infotexts (in closable callout boxes) with several entries, linking to the FAQ for more details.
The linked FAQ IDs are as well hardcoded and do not necessarily match to the freely editable FAQ entries. In addition, easy changes and additions to the info texts are not possible.

A new `Infotext` should be implemented, allowing for customized texts editable by managers.
- For each of the three index pages student, contributor, and grades (new) exactly one of these infotexts should exists.
- If an infotext is empty, no callout will be displayed on the respective page. Otherwise it will be shown like now.
- Each infotext should have a title that will be displayed as the heading.
- The infotexts should support HTML formatting just like FAQ entries.
- Both title and text must define an English and a German version.
- The infotexts should be editable on a new page that is only accessible for managers.

**Comment by Kakadus** [comment]
On which grades page should the new infotext be shown? Grades index (Semester choice) or Grades "overview" (Page when semester is chosen), or all of the above?
