### ISSUE TITLE
Replace reward point redemption dropdown with number input field

### ISSUE THREAD

**Issue by Kakadus** [e-valuation/EvaP#1788]
If a user selects an option, a new line is added and the selection spans two rows. This looks wrong.

A user can insert custom options. If the user inputs something invalid like "abcdef" or an empty string, only parts of "Please select"-placeholder is visible. This looks wrong as well.

**Comment by janno42** [comment]
And in addition the dropdown field is not right-aligned anymore. All this probably comes from the switch to Tom Select in #1758.
