### ISSUE TITLE
Replace asserts with contraints

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1800]
A couple of asserts/checks might be better expressed as constraints. I'm not sure there was a reason why we didn't do that.
* [start date must be before end date](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L467)
* [text and heading questions do not allow additional textanswers](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L1121)
* [TextAnswer's answer and original_answer must not be the same](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L1461)
* [Evaluation's _voter_count must be set iff _participant_count is set](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L620)
* [A bunch of validation when redeeming points](https://github.com/e-valuation/EvaP/blob/fc3f5b4390fbaf2aff2633dfbe61bbdd8e80c8b7/evap/rewards/tools.py#L36-L46)

_Originally posted by @karyon in https://github.com/e-valuation/EvaP/issues/1796#issuecomment-1221534890_

**Comment by florian-str** [comment]
Constrains as checklist:

- [ ] [start date must be before end date](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L467)
- [ ] [text and heading questions do not allow additional textanswers](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L1121)
- [ ] [TextAnswer's answer and original_answer must not be the same](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L1461)
- [ ] [Evaluation's _voter_count must be set iff _participant_count is set](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/models.py#L620)
- [ ] [A bunch of validation when redeeming points](https://github.com/e-valuation/EvaP/blob/fc3f5b4390fbaf2aff2633dfbe61bbdd8e80c8b7/evap/rewards/tools.py#L36-L46)

**Comment by niklasmohrin** [comment]
Closed by #1957
