### ISSUE TITLE
Modals fail to open

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1803]
Some modals (at least those in the contributor evaluation form) cannot be opened because the defined `onClick` references a non-existing method. Since 6aa3a5fcd49, the contact modal is opened via a button with a specific id instead of onClick.

**Comment by He3lixxx** [comment]
Applies to all contact modals that we didn't consider in #1770

* Contributor evaluation edit page "Request changes" and "Request creation of new account" buttons
  -> `createAccountRequestModalShow`, `changeEvaluationRequestModalShow`
* User profile page "Request changes" button
  -> `changeRequestModalShow`
