### ISSUE TITLE
User Import File Selection: Mime-Filter not working

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1807]
With Firefox 104.0.2, I don't get a file type filter in the file selection dialog that opens when clicking on "Select file" on the staff user import page.

Similarly to the semester import, it would be nice if users would get a correctly filtered file selection dialog.

**Comment by niklasmohrin** [comment]
Hint: We need to correctly set [the "accept" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept). This is already correctly configured for the "semester import" ;)
