### ISSUE TITLE
Position view selection buttons on top

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1816]
The pages `results_publication_detail` and `staff_evaluation_textanswers` have buttons to select different views on the top right.
When evaluations have long names that span over more than one line, the buttons are vertically positioned in the middle of the evaluation name.
Instead, they should stay on the top of the page.

**Comment by florian-str** [comment]
All sides where an input field of some sort is next to a textfield are effected by this issue.

**Comment by janno42** [comment]
On a quick glance I found only one other occurrence on `grades_semester_view`. Did you find more?

**Comment by richardebeling** [comment]
@janno42 The issue text above says `results_publication_detail` where it should be `results_evaluation_detail`, correct?

**Comment by fkoch-tgm** [comment]
Here are some Screenshots, I would like some input:

`grades_semester_view`:
<details><summary>Screenshots</summary>
<p>


Vorher:
![Screen Shot 2023-10-16 at 20 52 57](https://github.com/e-valuation/EvaP/assets/45557700/9920e9ad-227a-4342-8fe2-0b94485ff215)
Top-Aligned:
![Screen Shot 2023-10-16 at 20 52 25](https://github.com/e-valuation/EvaP/assets/45557700/9a9f3871-be15-4933-a899-d96a1859dd0d)

</p>
</details> 

`results_evaluation_details`:
<details><summary>Screenshots</summary>
<p>
Top:
![image](https://github.com/e-valuation/EvaP/assets/45557700/a715dc88-cc83-4d87-b1d4-c5698b51efa1)

Bottom:
![image](https://github.com/e-valuation/EvaP/assets/45557700/dc08c150-4fb5-4053-b0ae-b919e7c0cf65)

Center:
![image](https://github.com/e-valuation/EvaP/assets/45557700/fd55e211-af09-415d-944e-3bcb6b77b846)

</p>
</details> 


For `grades_semester_view` I personally think the centered version looks cleaner, but I am unsure.

For `results_evaluation_details` I would say that the bottom aligned version looks the best.

What do you think?

**Comment by fkoch-tgm** [comment]
Here also Screenshots for `staff_evaluation_textanswers`:
<details><summary>Screenshots</summary>
<p>
Top:
![image](https://github.com/e-valuation/EvaP/assets/45557700/8fca65de-9f09-4491-971b-dce5cfffbdff)


Bottom:
![image](https://github.com/e-valuation/EvaP/assets/45557700/ff6ca27f-5153-48f2-8c85-542f561e5fd3)


</p>
</details>

**Comment by janno42** [comment]
Thanks for the screenshots! I prefer a consistent position. Looking at the examples, I'd say always placing the buttons at the bottom looks best. What do you think?

**Comment by richardebeling** [comment]
Fixed in #2047
