### ISSUE TITLE
Navbar switch button tooltips

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1820]
The language buttons (EN/DE) and mode buttons (regular mode/staff mode) in the navbar should have styled bootstrap tooltips. The tooltips should be shown for enabled and disabled buttons.
Currently, only the enabled mode button has a correctly styled tooltip.

**Comment by islpriem** [comment]
The tooltips are deactivated by default for disabled buttons for a reason. On the one hand, the user cannot press the corresponding buttons anyway, and on the other hand, it seems rather confusing to label them according to the motto "if this button were clickable, you could perform the following action". In my opinion the tooltips for disabled buttons would be rather confusing and are not needed.

**Comment by janno42** [comment]
The current behavior is inconsistent in two ways:
- The language button's tooltips are not correctly styled.
- In other places, we also have tooltips for the currently selected option (see, e.g., the questionnaire list in staff mode).

To me, it seems useful to also explain what the current selection is in case the user isn't sure. So the tooltips should be shown regardless of the state.
