### ISSUE TITLE
Footer: Slogan centered in non-centered space between left and right buttons

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1824]
The slogan in the footer is not centered on the page, which (imo) looks a bit off if there is much space to its left and right.
![image](https://user-images.githubusercontent.com/13838962/196261930-c9d01ccd-a79e-4cdf-94b0-5bd37da60eef.png)

@janno42 is this intentional? I think we changed something about the left buttons in the past which made them wider, which probably moved the slogan a bit to the right?

I can see how we need the current centering approach if there is not much space available.

The same thing applies to the navigation items in the header, although its not as obvious there.

**Comment by janno42** [comment]
The decision was intentional at the time but I'm open to other suggestions as well :)

**Comment by He3lixxx** [comment]
We discussed offline and could not find a fully satisfying solution -- if we center the text on the page, it will look weird as soon as we reduce the width of the browser. Closing for now.
