### ISSUE TITLE
Evaluation badges not shown in grades_semester_view

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1845]
On the `grades_semester_view` page, the evaluation badges for degree and course type are currently not shown although they should be. The template is included on the page but the `evaluation` variable used in the current implementation is not set.

(reported in https://github.com/e-valuation/EvaP/pull/1842#discussion_r1059526690)

**Comment by florian-str** [comment]
The data appears to be available in the template, however it is not used by the badge template. Instead just a single empty badge gets included in the rendered html.

Manually adding/copying the used loop from `course_badge.html` without any further modification makes it work, but that's likely not the preferred way of using it.

The template is used successfully in `staff_semester_view`/ `staff_semester_view.html`, while not working for `grades_semester_view`.

**Comment by florian-str** [comment]
It turns out, that I misread the template name.
In `grades_semester_view` a template for evaluation badges was used, even though the page lists courses.
