### ISSUE TITLE
Frontend test `contact-modal-opens` flaky

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1848]
In #1809, I attempted to add a [frontend test](https://github.com/e-valuation/EvaP/blob/main/evap/static/ts/tests/frontend/contributor-evaluation-edit.ts) to make sure the issue doesn't reappear. Despite best efforts to write the test in such a way that CSS animations do not interfere with the test logic, the test still regularly fails in CI.

I don't know what to do about it apart from disabling/removing the test.

**Comment by niklasmohrin** [comment]
So there is https://docs.djangoproject.com/en/4.1/topics/testing/tools/#liveservertestcase which seems like what we want - they even provide an example that uses Selenium.

**Comment by He3lixxx** [comment]
> So there is https://docs.djangoproject.com/en/4.1/topics/testing/tools/#liveservertestcase which seems like what we want - they even provide an example that uses Selenium.

Oh, sorry, I wasn't focussed when we talked about this earlier: I think this is a different issue. The flaky test here is about us being unable to write test-assert-logic for what we want to assert with selenium. This would also be the case if we were driving selenium out of a python test case. The live server test case is about having a backend available during frontend tests, so we can observe database side effects of interactions with the UI.

For this issue, I think we should just remove the test if we can't find a way to make it work properly.
For the live server test case, I think this belongs to another issue, I think we should make a new one for that?

**Comment by niklasmohrin** [comment]
See #1854
