### ISSUE TITLE
Update the modal logic

### ISSUE THREAD

**Issue by florian-str** [e-valuation/EvaP#1851]
The modals in the current form can be difficult to use or debug.
Part of the issue is that the function names used for controlling the modals are created in the django-template by embedding the modal-id as a template-variable in the function signature.
This makes it difficult to find the references as they only exist at runtime.
As the django-based creation is also applied to the methods acting upon the user decision, it might require some workarounds or duplicate code if that particular use case does not fit the default flow.

**Comment by niklasmohrin** [comment]
Related: https://github.com/e-valuation/EvaP/pull/1837#discussion_r1046065367
