### ISSUE TITLE
Migrate to / support Keycloak

### ISSUE THREAD

**Issue by richardebeling** [e-valuation/EvaP#1856]
[HPI might migrate](https://myhpi.de/protokolle/2023-01-20) to Keycloak, we'd probably have to switch too, then.

I guess/hope there will be some kind of official announcement. Just opening this issue so we don't lose track of this.

Edit: Looks like keycloak also supports the OIDC protocol, we could probably get away without code changes then.

**Comment by He3lixxx** [comment]
Closing for now since there is still no dev access to an OIDC provider, and it might be much longer since we get that. Will reopen then.

**Comment by richardebeling** [comment]
Reopening as I overheard that the OIDC provider we're currently using is supposed to be taken down at the end of this month.

As far as I know, there is still not really a developer-friendly replacement for us. https://keycloak.hpi.de doesn't allow us to configure a realm and a client. The master realm will (correctly) deny our redirect-uri when attempting to use it for authentication (using the URLs specified at https://keycloak.hpi.de/realms/master/.well-known/openid-configuration).

IIRC, we had announcements that self-service will be allowed at some point, but I haven't heard of that in a while. In the mean time, the FSR even considered setting up their own instance in one of their recent meetings.

**Comment by richardebeling** [comment]
Using keycloak via the OpenID protocol/configuration works fine for us (using the URLs listed above), so it's just a configuration think and doesn't need any changes in our code.
