### ISSUE TITLE
Log voting timestamps

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1857]
To improve voting periods and reminders, the evaluation team needs statistical information on when evaluation votes are submitted.
For each submission, the following information should be logged:
- Evaluation
- Date and time of voting

An Excel export for the logged data must be provided from the staff semester page, including all vote log data for the semester. The exported file should contain the following columns:
- Evaluation id
- Course type
- Course degrees
- Vote end date
- Logged timestamp

**Comment by He3lixxx** [comment]
We would only need `(evaluation, timestamp)` pairs to be logged. However, from the `evaluation_evaluation_voters` table and its transaction IDs, people with database access can currently deduce the order in which users voted. This would basically allow to correlate the timestamps with the insertion order, so effectively we'd also store who voted at that time. We probably don't want that stored? In this case, we need to do some additional work to get rid of the transaction IDs in the voters table, just as we did in #1549.

An additional table with an `evaluation` and a `timestamp` field, combined with insertion-order-obfuscation on `evaluation_evaluation_voters`, should be fine from a data economy point of view IMO.
