### ISSUE TITLE
Fix button group borders

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1945]
In several places we have button groups where not all `btn`s are next to each other in the HTML code, so the CSS styling gets a bit weird. Either the border radii don't match (when setting the border on the grouping element) or the inner borders, where two buttons touch each other, are doubled (when setting the border on the buttons).
Some examples:
- language selection buttons in the navbar (border on grouping element)
- decision buttons and flag buttons on the text answer review page (border on buttons)

The expected styling would make sure that the radii match and that the inner borders are not doubled.

**Comment by richardebeling** [comment]
As discussed online, all to the best of my knowledge: Yes, that button group is one that the issue refers to.
In the current version, afaik, we only have the "border radius" issue, i.e. the button is not fully "filled" to the border. If that is fixed, there shouldn't be any need for changes to the border, I think the border-issue only occurred in another attempt to fix this border-radius issue.

(For reference: This is what is currently rendered on main for me, the borders look fine, but there is a very subtle border radius filling issue):
![image](https://github.com/e-valuation/EvaP/assets/13838962/f69722f7-c45d-44d6-b06c-28e9225b1525)

**Comment by fkoch-tgm** [comment]
There are two cases for this issue:

## 1. The buttons are nested inside form-tags (Navbar)
I fixed those buttons by removing all borders and border radii from the .btn and moving it into the .btn-group. This is done:

![image](https://github.com/e-valuation/EvaP/assets/45557700/a3de2489-b1d9-4477-8feb-806ae4dc420f)



## 2. General `box-shadow`s inside rounded corners:
It seems like if you have a inset `box-shadow` inside a button with rounded corners, it will not be rendered correctly in Firefox:
![image](https://github.com/e-valuation/EvaP/assets/45557700/a157d0ba-40e3-4750-89e6-a537e435ff80)


It seems like this is not an issue with Chromium:
![image](https://github.com/e-valuation/EvaP/assets/45557700/c319dccf-64a6-4acc-8353-371a8f29d8eb)

As this issue is with the rendering of the HTML itself, the only solution I can think of, is to switch to `background-image: radial-gradient(...)` instead.

**Comment by janno42** [comment]
It looks like parts of the original issue don't occur anymore. Sorry that we didn't include screenshots. The button's "filling" didn't reach the border in the corners, visually impacting even when not zooming in too much. This now looks fine for me in both Firefox and Chrome.

The issue also includes this situation on the "full" view on the text answer review page where (only some?) borders are doubled:
![image](https://github.com/e-valuation/EvaP/assets/1781719/4fd93bd3-0698-457e-a286-2cf65d977378)

**Comment by janno42** [comment]
I'd say the general box-shadows inside rounded corners aren't a problem we need to address.

**Comment by fkoch-tgm** [comment]
I am not sure if fixing the button overlap should be in the scope of this project. It seems like and underlying issue in Bootstrap and they do not plan to fix it: https://github.com/twbs/bootstrap/issues/25888

Maybe I can get the suggested fix to work, but if not an alternative would be to use multiple single-buttons or a styling that works without "visible" borders. (Like I used for the other buttons)

TODO@Self:
- [ ] Try to utilize jamesiscool's fix

**Comment by fkoch-tgm** [comment]
> It looks like parts of the original issue don't occur anymore. Sorry that we didn't include screenshots. The button's "filling" didn't reach the border in the corners, visually impacting even when not zooming in too much. This now looks fine for me in both Firefox and Chrome.
> 
> The issue also includes this situation on the "full" view on the text answer review page where (only some? - here between "Undecided" and "Delete") borders are doubled: ![image](https://private-user-images.githubusercontent.com/1781719/284346059-4fd93bd3-0698-457e-a286-2cf65d977378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTI3MzIsIm5iZiI6MTcwMTcxMjQzMiwicGF0aCI6Ii8xNzgxNzE5LzI4NDM0NjA1OS00ZmQ5M2JkMy0wNjk4LTQ1N2UtYTI4Ni0yY2Y2NWQ5NzczNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTc1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJhZTBjZmQ1M2UxY2I2Y2UwZDM1OTEzODM3YmUzMTM5ZDVlOWYxOGE4NGZhNmVjMzBkM2EyMDYwMWU5YzY0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fFnAcH6aWs7NTrrwoIHJxbeJPYLodi-QznPFEuJA8eM)
> 
> And in this case it looks even more weird, because buttons with different border colors overlap: ![image](https://private-user-images.githubusercontent.com/1781719/284365390-1481c42f-bdd2-49ce-84d0-f675fdf48069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTI3MzIsIm5iZiI6MTcwMTcxMjQzMiwicGF0aCI6Ii8xNzgxNzE5LzI4NDM2NTM5MC0xNDgxYzQyZi1iZGQyLTQ5Y2UtODRkMC1mNjc1ZmRmNDgwNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTc1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNkZTExMWZiNzQ4NGJkZWQxYmI1ZTdkYzg5OTg1OTg2ZWFjYzQ2ODMzM2U2M2NjNzdhNWQ0ZGNlYTZmZGQ2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y3T08i_39qB89NPxv_IQw-oGBNIjpxU4YeyxfmnRybw)

Just a quick note: For me the issue occurs only when setting my screen to 125% scaling (instead of 100%).

**Comment by fkoch-tgm** [comment]
I just found a similar issue on the live instance:

![vote-inputs with double borders](https://github.com/e-valuation/EvaP/assets/45557700/9be3dff4-c049-44a5-8267-52720b112c3f)

@fkoch-tgm I should test if I can reproduce it on the main branch
