### ISSUE TITLE
Replace `toggle_no_grades` with an idempotent alternative

### ISSUE THREAD

**Issue by niklasmohrin** [e-valuation/EvaP#1965]
Currently, there is a URL for toggling grade status of a course (`grades:toggle_no_grades`). Instead of having a toggle, we would like an idempotent operation, that is, the endpoint should be something like `grades:set_gets_grade_documents` where the desired boolean value is sent with the request. This way, two people who want to change the status don't revert each others action but instead set the same value.

**Comment by till2** [comment]
assign pls :)
