### ISSUE TITLE
Hotkey for flagging Textanswers

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1974]
When reviewing Textanswers in quick view, there are hotkeys for various operations. The newly implemented flagging (#1815) does not yet have a hotkey. The keys `F` and `D` should be added to set or remove a flag and should be added to the hotkey overview.

**Comment by niklasmohrin** [comment]
I linked my PR from yesterday, although there I currently have it as toggling the flag state. Which version do you prefer?

**Comment by janno42** [comment]
To be consistent with the other options (and to avoid getting an unwanted state by accidentally pressing the key more than once), there should be two separate keys and no toggle.
