### ISSUE TITLE
Fix burger menu icon color

### ISSUE THREAD

**Issue by dasGoogle** [e-valuation/EvaP#1986]
I recently had the issue that I was not able to find the menu button on my smartphone. 
I was in the process of writing an issue here when I noticed that it is actually still there but very hard to see as it is dark gray on a gray background. I remember there being more contrast but I am unsure. 

![image](https://github.com/e-valuation/EvaP/assets/16378455/5550662f-0b0f-4303-ab57-bdb01eb3938d)

Maybe you can consider making this button white (again) in the future?

**Comment by janno42** [comment]
Thanks for letting us know. I suspect this happened accidentally as part of a Bootstrap version change a while ago.
