### ISSUE TITLE
Reset evaluation after it started

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1991]
It is not currently possible to reset a running evaluation. If it turns out that the start of the evaluation period has been set too early, or if the evaluation has to be stopped for other reasons, a reset can currently only be done in the database.

The evaluation operation `revert_to_new` ("Revert to preparation" in the frontend), which resets the selected evaluation to state `new`, should be extended to other states. The operation should be allowed for all states from `prepared` to `reviewed` (all states except `new` and `published`) and should be called `reset_to_new` ("Reset evaluation" in the frontend).
When performing this operation, the user should be able to select a checkbox (default: checked) on the operation confirmation page to delete previously received answers.
If checked 
- all received answers (`TextAnswer` and `TextAnswerCounter`) for this evaluation will be deleted, and
- the `voters` list is cleared.

To prevent unintentional deletion of data, an additional confirmation modal should be displayed if the checkbox for the data to be deleted is set.

**Comment by fkoch-tgm** [comment]
@janno42 What UI style would you like best?

Extra Box, left-aligned:

![Screen Shot 2024-02-12 at 18 50 55](https://github.com/e-valuation/EvaP/assets/45557700/80c982d1-256b-4dad-b921-1bcf110f5c14)

Extra Box, centered:
![Screen Shot 2024-02-12 at 18 50 42](https://github.com/e-valuation/EvaP/assets/45557700/ac40171c-68d1-42d3-9df4-32505f74a0af)

Inside Buttonbox, centered:
![Screen Shot 2024-02-12 at 19 00 13](https://github.com/e-valuation/EvaP/assets/45557700/6ca66d5a-a7ec-47fe-b9e0-912c60a6152e)

**Comment by janno42** [comment]
"Extra Box, left-aligned" please :)
