### ISSUE TITLE
Export Reward Point Summary

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#2020]
A new button `Export reward points` should be added to the right of the text showing the number of available reward points on the staff reward points redemption events page. Clicking the button should download a CSV file containing a summary of the reward points.

This file should contain the two columns `Email` and `Points` for each user, listing the number of points currently available for that user (grantings minus redemptions) next to the user's email address. A line should only be added for users where this number of available points is not zero.

**Comment by joendter** [comment]
for the sake of consistency i think this should either result in a xls file or the `Export Redemptions` button should output a csv as well

**Comment by niklasmohrin** [comment]
We talked about this shortly in person and I agree partially: Since both sheets seem to be more on the "just data" than the "this is a spreadsheet with colors and stuff like that" side, I would even say that both should be CSV (as Excel can just open the CSV too). @janno42 What do you think?

**Comment by joendter** [comment]
Go ahead and unassign me

**Comment by janno42** [comment]
> We talked about this shortly in person and I agree partially: Since both sheets seem to be more on the "just data" than the "this is a spreadsheet with colors and stuff like that" side, I would even say that both should be CSV (as Excel can just open the CSV too). @janno42 What do you think?

I'd say CSV and just email and points is sufficient for the use case of this issue. The exported file is used internally for a quick overview of the current reward point status and we don't need the name information because the export is not used for, e.g., email generation. I also prefer CSV over Excel where we don't need formatting.
