### ISSUE TITLE
Check correctness of type annotations at test runtime

### ISSUE THREAD

**Issue by richardebeling** [e-valuation/EvaP#2066]
Plausible but wrong type annotations could give a false sense of security and are therefore (imho) more harmful than no type annotations. When we go through old code and annotate it (as we currently do in #2035), we might make mistakes that mypy does not catch, e.g. because calling code that uses other argument types simply isn't typed yet.

There is https://typeguard.readthedocs.io/en/latest/, which allows to inject run-time type checking into the program. I'm thinking of running the tests with this injected so that we can catch cases where we annotated stuff wrongly or too strictly.

One issue I can see is that this disallows passing mocked arguments in tests (especially if the validation uses `isinstance`). We might have to add manual exclusions for such cases. I wouldn't want this to be too invasive though, a best case scenario for me would be a handful of lines to inject the checking and maybe a handful more lines for manual exclusions where we use mocks.

@niklasmohrin @Kakadus thoughts?

**Comment by niklasmohrin** [comment]
Sounds like a cool Attempt :)

**Comment by Kakadus** [comment]
Its definitely a cool idea. I also heard of https://beartype.readthedocs.io/ which seems to do the same a bit different.
