### ISSUE TITLE
`sortable_form.js`: Convert to TypeScript, remove jQuery

### ISSUE THREAD

**Issue by richardebeling** [e-valuation/EvaP#2082]
As a follow-up to #2036, we should
* convert `evap/static/js/sortable_form.js` to TypeScript (consistent file naming should then use a hyphen instead of an underscore)
* remove the dependency on jQuery since the [underlying library](https://sortablejs.github.io) doesn't depend on it. This might be a bit more work as all usages of `makeFormSortable` use jquery types iirc.
    Edit: We also use django-dynamic-formsets / `jquery.formset.js` in there. I don't see a simple non-jquery replacement, so it's probably just fine to keep using jquery for that.

**Comment by richardebeling** [comment]
Marking as done for now as the main intention was `sortable_form.js`. Keeping jQuery around, for now, for django-dynamic-formsets/`jquery.formset.js`. Thanks @PFischbeck!

**Comment by janno42** [comment]
note: Sisyphus.js also uses jQuery
