### ISSUE TITLE
Proposed addition of Manual Installation Instructions for MacOS.

### ISSUE THREAD

**Issue by Asadali242** [e-valuation/EvaP#2088]
## Update: Manual Installation Instructions for macOS Users

This update introduces a comprehensive set of manual installation instructions tailored for macOS users who prefer to set up their EvaP development environment without Vagrant. Key additions include:

### Homebrew Installation
Guidance on installing Homebrew, the macOS package manager, to facilitate subsequent installations.

### Python and Dependencies
Steps to install Python and essential dependencies using Homebrew, ensuring a robust foundation for the EvaP environment.

### Virtual Environment Setup
Instructions for creating and activating a Python virtual environment, promoting best practices in dependency management.

### Package Installation
Details on updating critical Python packages (`pip`, `setuptools`, `wheel`) and installing project-specific requirements.

### PostgreSQL Setup
Comprehensive steps for installing, starting, and configuring PostgreSQL, including user creation and permission setting.

### Sass Installation
Instructions to install Sass, a key tool for stylesheet compilation.

### Database Configuration
Detailed steps for configuring the PostgreSQL database, including setting user passwords and accessing the command line interface.

### Test Data Loading
Guidelines on populating the database with test data, a crucial step for initializing the development environment.

### Running the Development Server
Final steps to launch the Django development server and access the EvaP application locally.

This update also includes a reminder for macOS users about potential system-specific issues and encourages utilizing the EvaP project's issue tracker and community forums for troubleshooting and support.
[Installation.md](https://github.com/e-valuation/EvaP/files/13625893/Installation.md)

**Comment by richardebeling** [comment]
Hey @Asadali242, thanks for making this. Unfortunately, we don't have the resources to maintain multiple development installation instructions for different platforms, especially if they contain duplication of the steps that are in [our setup script](https://github.com/e-valuation/EvaP/blob/main/deployment/provision_vagrant_vm.sh). The current steps for windows were also outdated, so we decided to remove them for now.

Is there a reason you didn't want to use the vagrant setup?

**Comment by richardebeling** [comment]
Closing for now as it seems stale -- feel free to comment/reopen if there's more stuff to discuss
