### ISSUE TITLE
Update user data on login

### ISSUE THREAD

**Issue by dasGoogle** [e-valuation/EvaP#2096]
Just another idea that comes from the FSR KeyCloak migration process:

The new FSR Keycloak offers first and last names that we try to keep updated with the actual names of the students. Thus, it might be feasible to update the display names on every login instead of only when creating the user. This would allow students to perform one name change via the KeyCloak for all FSR-related services. 

EvaP could still keep its self-service display name override feature so that names that were already changed remain correct. 

CC @lukasrad02 @jeriox

**Comment by richardebeling** [comment]
Sounds good to me. We could do logged updates of `first_name_given` (and maybe `last_name`) here:
https://github.com/e-valuation/EvaP/blob/0c833875cd3dbd787527c86b3d914f5358454aa0/evap/evaluation/auth.py#L154-L161

If we don't touch `first_name_chosen`, the name a user set on EvaP would always overwrite any updated values for `first_name_given`, which I think would be reasonable.

**Comment by janno42** [comment]
On login, `first_name_given` and `last_name` should be updated if the values for a user (identified by the same `email`) have changed.

A change in `email` can't be handled by EvaP and a user profile merge must be done manually in this case.

**Comment by janno42** [comment]
closing. name changes will be handled via the campus management system import instead.

**Comment by jeriox** [comment]
> closing. name changes will be handled via the campus management system import instead.

maybe we should verify if our requirement to have a self-service for the first name in the CMS is actually going to be implemented (cc @SilvanVerhoeven)
