### ISSUE TITLE
Evaluation feedback question in questionnaires

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#212]
The questionnaire of each course should provide a feedback question to write down remarks on the evaluation itself.
The information is meant to help the student representatives to update questionnaires and the evaluation process. The comments should only be visible to the student representatives.

**Comment by schumannd** [comment]
If there is a feedback form accessible from anywhere as implemented in #753, would an extra section in the questionnaire still be necessary? Or would a simple sentence like "If you have any issues filling out the questionnaire, don't hesitate to ask for help via the feedback-button" or something similar suffice?

**Comment by janno42** [comment]
see https://github.com/janno42/EvaP/commit/323f776c010b64a78487c639dba9593892fa4d87 for proposed changes to layout and functionality (save current user instead of email field and allow only logged in users to use the feedback form).

we do need some additional features as well:
- we need to save a time stamp for each entry
- staff users must be able to:
  - delete feedback entries
  - mark feedback entries as done
  - sort the table by timestamp, user, marked or not (we can use a datatable like for the results)

**Comment by karyon** [comment]
i think it would still be good to have since the entry barrier is lower. if there's an input field readily available people might just enter something there, whereas the feedback button is more like when people have specific issues.

this feature requires an option per course to disable that question for certain courses. this option should not be visible for editors, just staff members.

**Comment by karyon** [comment]
again to make this easier, just as in #170 we could simply send an email to the admins/staff, this way we don't need to store anything.

**Comment by janno42** [comment]
the new feature in #1507 is planned to be set up for certain keywords to tell students that they should use the feedback form for general evap feedback instead of the evaluation questionnaires.
