### ISSUE TITLE
"Delete Semester" (modal submit) button flicker-shows on staff semester page

### ISSUE THREAD

**Issue by richardebeling** [e-valuation/EvaP#2150]
@niklasmohrin we have an anti-flicker css rule in #1985:

https://github.com/e-valuation/EvaP/blob/e93b9f25227b078bf62d85115edf2979db315341/evap/static/scss/components/_confirmation-modal.scss#L1-L6

However, the selector here excludes the submit group. For me, on the staff semester index page, the red "Delete Semester" button thus shows for a short period during page load. Removing the ` > :not([slot="submit-group"])` part of the selector fixes the flickering for me, but I guess there was a reason for this exclusion?

**Comment by niklasmohrin** [comment]
First impressions: If I remember correctly, I intended to exclude the show-button slot, not the submit-group, not sure how it ended up like this. I can take a closer look  later
