### ISSUE TITLE
Documentation work

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#220]
what needs to be done:
- [x] a new structure. minimum is a structure/table of contents for the home page. better would be a concept of what detail to which part of the software goes where, and restructure the content accordingly.
- [x] translate [Questionnaires: Structure](https://github.com/fsr-itse/EvaP/wiki/Questionnaires:-Structure)
- [x] translate [Questionnaires: Assignment](https://github.com/fsr-itse/EvaP/wiki/Questionnaires:-Assignment)
- [x] [Users and their Rights](https://github.com/fsr-itse/EvaP/wiki/Users-and-their-Rights) is not up to date. at least editors are missing
- [x] one todo in [Questionnaires - Structure](https://github.com/fsr-itse/EvaP/wiki/Questionnaires:-Structure)
- [x] two todos in [Questionnaires - Assignment](https://github.com/fsr-itse/EvaP/wiki/Questionnaires:-Assignment)
- [x] add infos about rewards
- [x] perhaps replace some parts of [Installation](https://github.com/fsr-itse/EvaP/wiki/Installation) with references to the provision script
- [x] put the windows installation instructions in there
- [x] empty headlines in [User Management](https://github.com/fsr-itse/EvaP/wiki/User-Management)
- [x] dev-auth, createsuperuser
- [x] the three authentication backends
- [x] mention somewhere: a "no answer"-field exists, and why
- [x] ~~mention somewhere: student are allowed to vote only once~~

a dump of missing parts:
- [x] ~~translate [Stakeholder](https://github.com/fsr-itse/EvaP/wiki/Stakeholder)~~
- [x] add infos about grade publishing @janno42 
- [x] text answer visibility @janno42 
- [x] grade visibility plus the warning when low contributors @janno42 
- [x] special users and how they login @janno42
- [x] grade calculation @karyon 
- [x] ~~some general introduction to evap~~
- [x] User rights - reasons
- [x] data economy page @karyon 
    - archiving of courses/semesters, grade documents, users
    - reviewers vs managers
    - external users can see only their own courses
    - private courses
- [x] ~~approval by lecturers - reasons~~
- [x] ~~mention somewhere: why one responsible person in the import, and why should the responsible person (and not the FSR/the import) add more contributors~~
- [x] description of necessary cron jobs
- [x] ~~Evaluation process: some links to other pages~~
- [x] ~~default evaluation period~~
- [x] ~~extending the evaluation period, re-opening evaluations?~~

**Comment by He3lixxx** [comment]
https://github.com/fsr-itse/EvaP/wiki/Installation#productive-environment-cron-configuration
This page suggests that the cronjob to update the course stated should be started hourly.
On the staff semester course edit pages, a staff user can set a start of evaluation date precisely up to one minute. Either one of these should be changed, since right now, we are suggesting that a start time of 10:01 will be started at 10:01 but it with the example it might be started as late as 11:00.
How is the cronjob set up in production right now? @janno42
