### ISSUE TITLE
Participation progress bar

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#2233]
For the active semester, a progress bar for the total participation value (how many voters submitted evaluations) should be displayed. It should show the percentage of total voters divided by the total number of participants in that semester. The bar should be divided into several steps, each of which is labeled.

- A settings variable defines the steps. Each step has a percentage value and a label (e.g., `0.4: "1 000 €"`, `0.8: "5 000 €"`).
- The highest step defines at which value the bar is filled (in the example above, a participation value of `0.8` would be represented by a completely filled bar.
- The progress bar can be turned off by setting the variable to an empty value.
- Two settings variables `EXCLUDED_COURSE_TYPE_IDS` and `EXCLUDED_EVALUATION_IDS` define which evaluations are not taken into account when calculating the participation value.
- Evaluations are only taken into account if they _do not meet any_ of these conditions:
    - They are excluded by their ID
    - They have an excluded CourseType
    - They are a `single_result`
    - They are in a state lower than `APPROVED`
    - They are `not rewarded`
    - They are `private`

The progress bar should be displayed at the top of the student index page.
An explanatory text that is defined in a settings variable (HTML formatting should be supported) should be displayed in a (initially collapsed) text area below the progress bar.
Also, the text "The last evaluation was submitted N minutes/hours/days ago" should be displayed next to it.

**Comment by Kakadus** [comment]
> They are `private`

I think only a `Course` can be private
