### ISSUE TITLE
Loading of backup fails due to nullable `natural_key`: the `USERNAME_FIELD`

### ISSUE THREAD

**Issue by Kakadus** [e-valuation/EvaP#2247]
Loading a larger backup which contains multiple users with their email `None` fails with a unique constraint failure.

This should be reproduced by expanding the testdata accordingly and fixed by replacing the default natural key with `(self.pk,settings.USERNAME_FIELD)`

**Comment by richardebeling** [comment]
Short summy of what happened, as it took me a moment to puzzle it together again:

We would like to use `AbstractBaseUser` as base class for our UserProfiles, as [recommended by the docs](https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#specifying-a-custom-user-model), but this class [implements `natural_key` to just return `USERNAME_FIELD`](https://github.com/django/django/blob/40d5516385448a73426aad396778f369a363eda9/django/contrib/auth/base_user.py#L77). Our `USERNAME_FIELD` was just set to be the optional "email" field, [which is legal according to the docs](https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD):
> The field must be unique (e.g. have unique=True set in its definition), unless you use a custom authentication backend that can support non-unique usernames.

For backups, we serialize models with natural keys, as [recommended by the docs](https://docs.djangoproject.com/en/5.1/topics/serialization/#natural-keys). This loses data with models that have a ForeignKey to UserProfile, as just storing `[None]` doesn't retain the referenced user. (Loading then fails with a unique constraint validation after getting the user profile by natural key, but the root problem is the information loss on serialization).

So basically django documents that non-uniqueness of the `USERNAME_FIELD` is legal, but their `AbstractBaseUser` breaks when using natural key serialization if any model has a foreign key to it.

There is no easy way to opt-out of natural key serialization for a model, django hardcodes in various places that if `natural_key` exists, it is called and used. Django also hardcodes that `pk` will not be serialized, even if `natural_key()` includes it in the return value.

We reported a bug saying that the documentation is wrong if the current behavior is desired in [ticket 35729](https://code.djangoproject.com/ticket/35729) and were asked to open [a discussion](https://forum.djangoproject.com/t/how-to-serialize-user-profiles-without-natural-keys/34447) instead, which ended up being ignored on the docs issue. We were told to build a custom UserProfile model without using AbstractBaseUser instead.
