### ISSUE TITLE
Open evaluations in new tabs

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#2292]
Control-clicking on evaluation rows on student index and contributor index should open the pages in new tabs (see results page for an example).
Currently, clicking reloads the page.

**Comment by niklasmohrin** [comment]
I think this is a regression introduced in #2117

**Comment by janno42** [comment]
> I think this is a regression introduced in #2117

You mean the frontend change that I didn't test? 😅

**Comment by niklasmohrin** [comment]
I stand by my change and blame the reviewers :sunglasses:
