### ISSUE TITLE
Vagrant VM Instructions Outdated 

### ISSUE THREAD

**Issue by zooomey** [e-valuation/EvaP#2340]
In the wiki, there are instructions to follow instructions to create the Vagrant VM, and a few references to using the Vagrant VM, however, it seems to be outdated: [Wiki Link](https://github.com/e-valuation/EvaP/wiki/Installation#:~:text=After%20cloning%20the%20repository%2C%20follow%20the%20steps%20in%20the%20script%20used%20to%20create%20the%20Vagrant%20VM.)

Specifically, links to this file which does not exist:
https://github.com/e-valuation/EvaP/blob/main/deployment/provision_vagrant_vm.sh

**Comment by richardebeling** [comment]
Thanks, fixed. We've recently switched infrastructure to setup dev environments, up-to-date instructions can be found in the [readme](https://github.com/e-valuation/EvaP?tab=readme-ov-file#development-setup).

This hasn't been around for long, so you might encounter errors that we haven't observed yet. Feel free to contact us for help if something doesn't work with the setup.
