### ISSUE TITLE
FATAL: role "evap" does not exist during macOS setup

### ISSUE THREAD

**Issue by FaL397** [e-valuation/EvaP#2346]
### **Description**
While setting up the EvaP project on macOS, I encountered the following error when trying to connect to the database using the `evap` role:

```
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL: role "evap" does not exist
```

This occurs even after following the setup instructions to create the `evap` role and database.

---

### **Steps to Reproduce**

1. Clone the EvaP repository:
   ```bash
   git clone --recurse-submodules https://github.com/e-valuation/EvaP.git
   cd EvaP
   ```

2. Set up `nix` and the environment as per the instructions.

3. Start PostgreSQL:
   ```bash
   pg_ctl -D ~/postgresql-data start
   ```

4. Log in as a superuser and create the `evap` role and database:
   ```sql
   CREATE ROLE evap WITH LOGIN PASSWORD 'evap';
   CREATE DATABASE evap OWNER evap;
   GRANT ALL PRIVILEGES ON DATABASE evap TO evap;
   ```

5. Attempt to connect to the database as the `evap` user:
   ```bash
   psql -U evap -d evap
   ```

---

### **Expected Behavior**

The `psql` command should successfully connect to the `evap` database using the `evap` role.

---

### **Actual Behavior**

The connection fails with the error:
```
FATAL: role "evap" does not exist
```

---

### **Environment Details**

- **Operating System:** macOS (Version: [Specify macOS version])
- **PostgreSQL Version:** 16.4
- **Python Version:** 3.10
- **nix Version:** [Specify installed nix version]

---

### **Troubleshooting Steps Tried**

1. Verified that the `evap` role exists:
   ```bash
   psql -U postgres -c '\du'
   ```
   Result: `evap` role does not appear in the list, even after creation.

2. Recreated the `evap` role and database:
   ```sql
   DROP DATABASE IF EXISTS evap;
   DROP ROLE IF EXISTS evap;
   CREATE ROLE evap WITH LOGIN PASSWORD 'evap';
   CREATE DATABASE evap OWNER evap;
   GRANT ALL PRIVILEGES ON DATABASE evap TO evap;
   ```

3. Reinitialized PostgreSQL:
   ```bash
   rm -rf ~/postgresql-data
   initdb -D ~/postgresql-data
   pg_ctl -D ~/postgresql-data start
   ```

Despite these steps, the error persists.

---

### **Request for Help**

I suspect there may be an issue with PostgreSQL role persistence or compatibility with macOS configurations. Could the EvaP community provide guidance on resolving this?

---

### **Logs**

Relevant logs from `~/postgresql-data/postgresql.log`:
```
2024-11-19 18:22:01.504 EST [44020] FATAL:  role "evap" does not exist
```

---

### **Potential Suggestions**
If this is a known issue, it would be helpful to include detailed steps in the documentation for creating roles and troubleshooting database connections on macOS.

---

Let me know if this format works or needs adjustments!

<img width="627" alt="Screenshot 2024-11-20 at 10 51 32 AM" src="https://github.com/user-attachments/assets/42f477b7-eacd-46ac-9ae9-f64533c20cc1">
<img width="1174" alt="Screenshot 2024-11-19 at 5 30 20 PM" src="https://github.com/user-attachments/assets/992a92a7-6361-433e-961e-a2f22b9b6cc2">

**Comment by FaL397** [comment]
Thank you so much your response. Yes, I did modified `evap/localsettings.py` because it wasn't working when following the instructions. I was having issues when `nix run .#services-full`.

I will try your solution and follow up with results.

**Comment by FaL397** [comment]
UpdateL=: `nix run .#services-full -- --tui=false` did the work. Thanks. Closing the issue.

**Comment by richardebeling** [comment]
> I was having issues when `nix run .#services-full` as well.

This would be the interesting part from our side. We can't really help you with your local postgres setup, but if something with our setup is broken, we would like to fix it.

> Update= `nix run .#services-full -- --tui=false` did the work.

The `--tui=false` flag just changes the console output to a text-log version that is more suitable for posting here on GitHub, it shouldn't affect the environment that will be set-up. As far as we are concerned, this basically means "I ran it again and now it works", which doesn't allow us to figure out what went wrong in the first place.

**Comment by FaL397** [comment]
@richardebeling 

 It was instructed on MacOS, to install nix using the [Determinate Nix Installer](https://install.determinate.systems/). 
 
  ran:
`curl --proto '=https' --tlsv1.2 -sSf -L \
  https://install.determinate.systems/nix | sh -s -- install --determinate`
  
then 
` nix run .#services-full  `

was getting ` command not found: nix` error

Hope this helps

**Comment by niklasmohrin** [comment]
So concluding this, it looks like a mistake during the nix installation, either from the installer or by not following some instruction. In either case, unless this problem reoccurs frequently, it's not a problem with our setup and we won't track it any further.
