### ISSUE TITLE
Link to FAQ next to the evaluation period fields

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#288]
Lecturers should get a hint on how to define the evaluation period on their review page by placing a link to the appropriate FAQ question "How should the evaluation period be defined?".

**Comment by karyon** [comment]
have a look at https://stackoverflow.com/questions/10706296/how-do-i-input-html-into-the-help-text-of-a-django-form-field, it seems like with `mark_safe` adding URLs should just work.

**Comment by janno42** [comment]
evaluation periods are carefully set by most contributors and are individually checked by the evaluation team if certain constraints are important to be met. so this isn't really an issue anymore.
