### ISSUE TITLE
Multiple text answers for a single question

### ISSUE THREAD

**Issue by j4yk** [e-valuation/EvaP#612]
When I type long texts into a text box for a single question, some parts might identify me as the author (e.g. because of intended or unintended references to prior mail conversations or particular exercise solutions). It would be nice if I could split such paragraphs into a separate answer, so they cannot be linked to the rest of my answer.

To the recipient of the feedback it would appear that there are two (or more) separate answers to the question. As those could also come from different students, the suspension of anonymity would not necessarily leak from one part of the answer to the other parts.

Not sure if this is generally desirable for all actors, though. Of course, care must be taken by the author to not produce cross-references between the split parts (similar to "see above"-problem among answers to distinct questions). And a good idea for the UI to invoke a split is necessary.

Workaround is, of course, to avoid statements which could identify me as the author but that can be tricky if you do want to provide feedback for a specific case.

**Comment by karyon** [comment]
a possible UI for this would be: some plus sign somewhere near each text answer box, adding a second box. this would need an accompanying explanation what this actually does.

also, we would need to shuffle responses at some point. right now, the two added answers would most likely show up one behind the other in the answers.

**Comment by janno42** [comment]
Shuffling was implemented by now.

The following has been decided for this feature: Under each text answer a button will be added that adds additional text boxes. This enables users to submit multiple individual text answers for one question.
For review purposes (to prevent one user spamming the same answer over and over) text answers need to be grouped by user (see #1130).

**Comment by janno42** [comment]
Closed, see #1130
