### ISSUE TITLE
Result exporter is not tested

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#999]
there are some tests in staff/tests/test_views that test the exporter, but it seems like it is not creating any questionnaires. large portions of the results exporter are not covered therefore.

**Comment by niklasmohrin** [comment]
Things to test:
- [ ] Multiple sheets
- [ ] `include_unpublished`
- [ ] `include_not_enough_voters`
- [ ] exclusion of single-result evaluations
- [ ] probably
